### ISSUE TITLE
minor: shorten a warning

### ISSUE THREAD

**Issue by toralf** [klausman/lib_users#4]
The following could be shortened for user root : 
`
mr-fox ~ # lib_users -s
Warning: Some files could not be read. Note that lib_users has to be run as
root to get a full list of deleted in-use libraries.

mr-fox ~ # whoami
root
`
Happens probably for things like this ? 

`mr-fox ~ # lib_users -s
Warning: Some files could not be read. Note that lib_users has to be run as
root to get a full list of deleted in-use libraries.

13159 "afl-fuzz -i /home/torproject/tor-fuzz-corpora//extrainfo -o ./work/20170521-190903_a18b41cc7_extrainfo -m 50000000 -- /home/torproject/tor//src/test/fuzz/fuzz-extrainfo" uses /home/torproject/work/20170521-190903_a18b41cc7_extrainfo/queue/id:000005,orig:04a4394b5a10a3311ebee52d19cd24793860534f3a951a5369905802a293d0d2
`

**Comment by klausman** [comment]
Yeah, I guess this should be either no message at all, or one that explains that things may be racy, even with UID 0. I have a slight preference for the former, what do you think?

**Comment by toralf** [comment]
yep, it is indep of UID 0 - the race is the message

**Comment by toralf** [comment]
I was just thinking about someting like 

print "Warning: Some files could not be read."
if [[ UID != 0 ]] then print "Note that lib_users has to be run as
root to get a full list of deleted in-use libraries."

**Comment by klausman** [comment]
Fixed by commit f56cf2d
